name = "SPTLikelihoods"
uuid = "843b1235-59c8-469d-b900-1f4e1bdb4f86"
authors = ["Marco Bonici <bonici.marco@gmail.com>, Marius Millea <mariusmillea@gmail.com>"]
version = "0.3.0"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
CMBForegrounds = "fc0df5e6-91e0-40ab-a79d-ad91d7e99724"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"

[compat]
CMBForegrounds = "0.1.0"
